[project]
name = "rrh-backend"
version = "0.0.2"
requires-python = ">=3.11"
dependencies = ["fastapi>=0.115","uvicorn[standard]>=0.30","httpx>=0.27","pydantic>=2.7","sentence-transformers>=3.0.1","numpy>=1.26"]
